global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "water_lab_api"
    metrics_path: "/metrics"

    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/api_token

    static_configs:
      - targets:
          - "api:8000"